### login
POST {{api}}/users/login
Content-Type: application/json

{
  "email": "alice@gmail.com",
  "password": "12345678"
}

> {%
  client.global.set("auth_token", response.body.token);
%}


### Get all users
GET {{api}}/users


### Update me
PATCH {{api}}/users/update-me
Content-Type: application/json

{
  "name": "James",
  "role": "PREMIUM_USER"
}

### Delete current user
DELETE {{api}}/users/delete-me
Authorization: Bearer {{auth_token}}


### Get a user
GET {{api}}/users/5

### Create a user
POST {{api}}/users
Content-Type: application/json

{
  "name": "Rania Chick",
  "email": "rania@gmail.com",
  "password": "123456",
  "role": "PREMIUM_USER"
}

